### ISSUE TITLE
启动python webui_mix.py 报一下错误如何处理呢？

### ISSUE THREAD

**Issue by jbigdata** [6drf21e/ChatTTS_colab#101]
Traceback (most recent call last):
  File "/Users/liangwan/AImanager/tts/ChatTTS_colab/webui_mix.py", line 46, in <module>
    chat = load_chat_tts_model(source=args.source, local_path=args.local_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/liangwan/AImanager/tts/ChatTTS_colab/tts_model.py", line 25, in load_chat_tts_model
    chat.load_models(source=source, force_redownload=force_redownload, custom_path=local_path, compile=False)
    ^^^^^^^^^^^^^^^^
AttributeError: 'Chat' object has no attribute 'load_models'. Did you mean: 'download_models'?
(chattts) liangwan@swdeMacBook-Pro ChatTTS_colab % python webui_mix.py
Loading ChatTTS model...
Traceback (most recent call last):
  File "/Users/liangwan/AImanager/tts/ChatTTS_colab/webui_mix.py", line 46, in <module>
    chat = load_chat_tts_model(source=args.source, local_path=args.local_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/liangwan/AImanager/tts/ChatTTS_colab/tts_model.py", line 25, in load_chat_tts_model
    chat.load_models(source=source, force_redownload=force_redownload, custom_path=local_path, compile=False)
    ^^^^^^^^^^^^^^^^
AttributeError: 'Chat' object has no attribute 'load_models'. Did you mean: 'download_models'?

**Comment by shichao-an** [comment]
I realized this step didn't execute properly:

```
!git checkout -q e6412b1
```

Make sure the branch/commit of ChatTTS is switched to `e6412b1`
