### ISSUE TITLE
AttributeError: BertTokenizerFast has no attribute pad_token 如何解决呢？

### ISSUE THREAD

**Issue by jbigdata** [6drf21e/ChatTTS_colab#102]
['四川美食确实以辣闻名，但也有不辣的选择。比如甜水面、赖汤圆、蛋烘糕、叶儿粑等，这些小吃口味温和，甜而不腻，也很受欢迎。', '我是一个充满活力的人，喜欢运动，喜欢旅行，喜欢尝试新鲜事物。我喜欢挑战自己，不断突破自己的极限，让自己变得更加强大。', '罗森宣布将于7月24日退市，在华门店超6000家']
speaker_type: seed
Inferring audio for seed=1870:   0%|                                                                                                                                                                                                | 0/3 [00:00<?, ?steps/s]INFO:ChatTTS.core:All initialized.
WARNING:ChatTTS.core:Package WeTextProcessing not found!
WARNING:ChatTTS.core:Run: conda install -c conda-forge pynini=2.1.5 && pip install WeTextProcessing
Inferring audio for seed=1870:   0%|                                                                                                                                                                                                | 0/3 [00:00<?, ?steps/s]
Traceback (most recent call last):
  File "/Users/liangwan/miniconda3/envs/ChatTTS_colab/lib/python3.11/site-packages/gradio/queueing.py", line 624, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/liangwan/miniconda3/envs/ChatTTS_colab/lib/python3.11/site-packages/gradio/route_utils.py", line 323, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/liangwan/miniconda3/envs/ChatTTS_colab/lib/python3.11/site-packages/gradio/blocks.py", line 2043, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/liangwan/miniconda3/envs/ChatTTS_colab/lib/python3.11/site-packages/gradio/blocks.py", line 1590, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/liangwan/miniconda3/envs/ChatTTS_colab/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/liangwan/miniconda3/envs/ChatTTS_colab/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2505, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/Users/liangwan/miniconda3/envs/ChatTTS_colab/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 1005, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/liangwan/miniconda3/envs/ChatTTS_colab/lib/python3.11/site-packages/gradio/utils.py", line 865, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "/Users/liangwan/ChatTTS_colab/webui_mix.py", line 212, in audio_interface
    seeds = generate_seeds(num_seeds, texts, progress.tqdm)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/liangwan/ChatTTS_colab/webui_mix.py", line 139, in generate_seeds
    filename = generate_audio_for_seed(chat, seed, texts, 1, 5, "[oral_2][laugh_0][break_4]", None, 0.3, 0.7, 20)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/liangwan/ChatTTS_colab/tts_model.py", line 110, in generate_audio_for_seed
    wavs = chat.infer(batch, params_infer_code=_params_infer_code, params_refine_text=params_refine_text,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/liangwan/ChatTTS_colab/ChatTTS/core.py", line 259, in infer
    return next(res_gen)
           ^^^^^^^^^^^^^
  File "/Users/liangwan/ChatTTS_colab/ChatTTS/core.py", line 187, in _infer
    text_tokens = refine_text(
                  ^^^^^^^^^^^^
  File "/Users/liangwan/ChatTTS_colab/ChatTTS/infer/api.py", line 97, in refine_text
    text_token = models['tokenizer'](text, return_tensors='pt', add_special_tokens=False, padding=True).to(device)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/liangwan/miniconda3/envs/ChatTTS_colab/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 2860, in __call__
    encodings = self._call_one(text=text, text_pair=text_pair, **all_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/liangwan/miniconda3/envs/ChatTTS_colab/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 2948, in _call_one
    return self.batch_encode_plus(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/liangwan/miniconda3/envs/ChatTTS_colab/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 3141, in batch_encode_plus
    padding_strategy, truncation_strategy, max_length, kwargs = self._get_padding_truncation_strategies(
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/liangwan/miniconda3/envs/ChatTTS_colab/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 2761, in _get_padding_truncation_strategies
    if padding_strategy != PaddingStrategy.DO_NOT_PAD and (self.pad_token is None or self.pad_token_id < 0):
                                                           ^^^^^^^^^^^^^^
  File "/Users/liangwan/miniconda3/envs/ChatTTS_colab/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 1104, in __getattr__
    raise AttributeError(f"{self.__class__.__name__} has no attribute {key}")
AttributeError: BertTokenizerFast has no attribute pad_token

**Comment by fly51fly** [comment]
! pip install --upgrade --force-reinstall -q transformers==4.42.4

**Comment by sincejuly666** [comment]
> ! pip install --upgrade --force-reinstall -q transformers==4.42.4

可以解决问题

**Comment by victorxys** [comment]
可解
