### ISSUE TITLE
win10整合包，双击运行.bat，抛异常FileNotFoundError

### ISSUE THREAD

**Issue by printff** [6drf21e/ChatTTS_colab#20]
Windows 10 专业版
22H2
19045.4412
解压ChatTTS_colab_offline-003.7z到c:\ai目录下。

```
C:\ai\ChatTTS_colab_offline>runtime\python.exe webui_mix.py  --source local --local_path models
Traceback (most recent call last):
  File "C:\ai\ChatTTS_colab_offline\webui_mix.py", line 16, in <module>
    from tts_model import load_chat_tts_model, clear_cuda_cache, deterministic, generate_audio_for_seed
  File "C:\ai\ChatTTS_colab_offline\tts_model.py", line 1, in <module>
    import ChatTTS
  File "C:\ai\ChatTTS_colab_offline\ChatTTS\__init__.py", line 1, in <module>
    from .core import Chat
  File "C:\ai\ChatTTS_colab_offline\ChatTTS\core.py", line 7, in <module>
    from vocos import Vocos
  File "C:\ai\ChatTTS_colab_offline\runtime\lib\site-packages\vocos\__init__.py", line 1, in <module>
    from vocos.pretrained import Vocos
  File "C:\ai\ChatTTS_colab_offline\runtime\lib\site-packages\vocos\pretrained.py", line 9, in <module>
    from vocos.feature_extractors import FeatureExtractor, EncodecFeatures
  File "C:\ai\ChatTTS_colab_offline\runtime\lib\site-packages\vocos\feature_extractors.py", line 4, in <module>
    import torchaudio
  File "C:\ai\ChatTTS_colab_offline\runtime\lib\site-packages\torchaudio\__init__.py", line 2, in <module>
    from . import _extension  # noqa  # usort: skip
  File "C:\ai\ChatTTS_colab_offline\runtime\lib\site-packages\torchaudio\_extension\__init__.py", line 38, in <module>
    _load_lib("libtorchaudio")
  File "C:\ai\ChatTTS_colab_offline\runtime\lib\site-packages\torchaudio\_extension\utils.py", line 60, in _load_lib
    torch.ops.load_library(path)
  File "C:\ai\ChatTTS_colab_offline\runtime\lib\site-packages\torch\_ops.py", line 933, in load_library
    ctypes.CDLL(path)
  File "ctypes\__init__.py", line 374, in __init__
FileNotFoundError: Could not find module 'C:\ai\ChatTTS_colab_offline\runtime\Lib\site-packages\torchaudio\lib\libtorchaudio.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
```

事实上，这个文件是存在的：
```
C:\Users\sun>dir C:\ai\ChatTTS_colab_offline\runtime\Lib\site-packages\torchaudio\lib\libtorchaudio.pyd
 驱动器 C 中的卷没有标签。
 卷的序列号是 5615-C7E5

 C:\ai\ChatTTS_colab_offline\runtime\Lib\site-packages\torchaudio\lib 的目录

2024/03/06  22:54         2,639,360 libtorchaudio.pyd
               1 个文件      2,639,360 字节
               0 个目录 134,852,808,704 可用字节
```

**Comment by hwwff** [comment]
我也有这个问题，配置是intel 8300h，四核，12G内存
