### ISSUE TITLE
error when running api.py on linux

### ISSUE THREAD

**Issue by ramishi** [6drf21e/ChatTTS_colab#45]
this error when running api.py, running webui_mix.py is fine:

INFO:ChatTTS.core:Load from local: models
Traceback (most recent call last):
  File "/ChatTTS_colab/api.py", line 342, in <module>
    chat.load_models(source="local", local_path="models")
  File "/ChatTTS_colab/ChatTTS/core.py", line 62, in load_models
    self._load(**{k: os.path.join(download_path, v) for k, v in OmegaConf.load(os.path.join(download_path, 'config', 'path.yaml')).items()}, **kwargs)
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ChatTTS/.conda/lib/python3.11/site-packages/omegaconf/omegaconf.py", line 189, in load
    with io.open(os.path.abspath(file_), "r", encoding="utf-8") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/ChatTTS_colab/models/config/path.yaml'

**Comment by killy001** [comment]
same error
