### ISSUE TITLE
「问题」流式传输出现了错误：

### ISSUE THREAD

**Issue by aklws** [6drf21e/ChatTTS_colab#48]
Traceback (most recent call last):
  File "/home/zjy/miniconda3/envs/chattts/lib/python3.10/site-packages/gradio/queueing.py", line 521, in process_events
    response = await route_utils.call_process_api(
  File "/home/zjy/miniconda3/envs/chattts/lib/python3.10/site-packages/gradio/route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/zjy/miniconda3/envs/chattts/lib/python3.10/site-packages/gradio/blocks.py", line 1945, in process_api
    result = await self.call_function(
  File "/home/zjy/miniconda3/envs/chattts/lib/python3.10/site-packages/gradio/blocks.py", line 1525, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/home/zjy/miniconda3/envs/chattts/lib/python3.10/site-packages/gradio/utils.py", line 655, in async_iteration
    return await iterator.__anext__()
  File "/home/zjy/miniconda3/envs/chattts/lib/python3.10/site-packages/gradio/utils.py", line 648, in __anext__
    return await anyio.to_thread.run_sync(
  File "/home/zjy/miniconda3/envs/chattts/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/zjy/miniconda3/envs/chattts/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "/home/zjy/miniconda3/envs/chattts/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "/home/zjy/miniconda3/envs/chattts/lib/python3.10/site-packages/gradio/utils.py", line 631, in run_sync_iterator_async
    return next(iterator)
  File "/home/zjy/miniconda3/envs/chattts/lib/python3.10/site-packages/gradio/utils.py", line 814, in gen_wrapper
    response = next(iterator)
  File "/home/zjy/ChatTTS_colab/webui_mix.py", line 375, in generate_tts_audio_stream
    wavs_gen = chat.infer(text, params_infer_code=params_infer_code, params_refine_text=params_refine_text,
TypeError: Chat.infer() got an unexpected keyword argument 'stream'

**Comment by v3ucn** [comment]
你的ChatTTS模块得更新，和官方的同步

**Comment by aklws** [comment]
我现在用了整合包，可以流式了，但是字一多就爆显存，我的系统是ubuntu22.04,显卡3070ti,显存8g,桌面是xfce.

**Comment by 6drf21e** [comment]
我这边也爆😓
等官方更新吧 或者用伪流式

**Comment by wstsr333** [comment]
请问是什么整合包啊

**Comment by aklws** [comment]
b站上找到的
