### ISSUE TITLE
0.0.6版出现无法继续工作的问题，汇报

### ISSUE THREAD

**Issue by Jimi-from-mars** [6drf21e/ChatTTS_colab#50]
用0.0.6版本的长文本模式测试了几个pt文件以后，突然出现如下错误提示，无法再正常运行，重启也不行。只有彻底删除整个chattts文件夹，重新解压后才能正常运行。这个状况已经出现两次。我的显卡是3060，12G显存，系统是windows 10。参数都没有改动，只有批大小设置为6了。

True 0 种子 <gradio.layouts.tabs.Tab object at 0x00000261C0785940>
paragraph 红色联合的战士们欢呼起来，几个人冲到楼下，掀开四二八的旗帜，抬起下面纤小的遗体，做为一个战利品炫耀地举了一段，然后将她高高地扔向大院的铁门，铁门上带尖的金属栅条大部分在武斗初期就被抽走当梭标了，剩下的两条正好挂住了她，那一瞬间，生命似乎又回到了那个柔软的躯体。红色联合的红卫兵们退后一段距离，将那个挂在高处的躯体当靶子练习射击，密集的子弹对她来说已柔和如雨，不再带来任何感觉，她那春藤般的手臂不时轻挥一下，仿佛拂去落在身上的雨滴，直到那颗年轻的头颅被打掉了一半，仅剩的一只美丽的眼睛仍然凝视着一九六七年的蓝天，目光中没有痛苦，只有凝固的激情和渴望。
sentences ['红色联合的战士们欢呼起来，几个人冲到楼下，掀开四二八的旗帜，抬起下面纤小的遗体，做为一个战利品炫耀地举了一段，然后将她高高地扔向大院的铁门，铁门上带尖的金属栅条大部分在武斗初期就被抽走当梭标了，剩下的两条正好挂住了她，那一瞬间，生命似乎又回到了那个柔软的躯体', '。', '红色联合的红卫兵们退后一段距离，将那个挂在高处的躯体当靶子练习射击，密集的子弹对她来说已柔和如雨，不再带来任何感觉，她那春藤般的手臂不时轻挥一下，仿佛拂去落在身上的雨滴，直到那颗年轻的头颅被打掉了一半，仅剩的一只美丽的眼睛仍然凝视着一九六七年的蓝天，目光中没有痛苦，只有凝固的激情和渴望', '。', '']
result ['红色联合的战士们欢呼起来，几个人冲到楼下，掀开四二八的旗帜，抬起下面纤小的遗体，做为一个战利品炫耀地举了一段， 然后将她高高地扔向大院的铁门，铁门上带尖的金属栅条大部分在武斗初期就被抽走当梭标了，剩下的两条正好挂住了她，那一瞬间，生命似乎又回到了那个柔软的躯体。', '红色联合的红卫兵们退后一段距离，将那个挂在高处的躯体当靶子练习射击，密集的子弹对她来说已柔和如雨，不再带来任何感觉，她那春藤般的手臂不时轻挥一下，仿佛拂去落在身上的雨滴，直到那颗年轻的头颅被打掉了一半，仅剩的一只美丽的眼睛仍然凝视着一九六七年的蓝天，目光中没有痛苦，只有凝固的激情和渴望。']
INFO:root:found existing fst: G:\AI-test\ChatTTS_colab_offline\runtime\lib\site-packages\tn\zh_tn_tagger.fst
INFO:root:                    G:\AI-test\ChatTTS_colab_offline\runtime\lib\site-packages\tn\zh_tn_verbalizer.fst
INFO:root:skip building fst for zh_normalizer ...
INFO:root:found existing fst: G:\AI-test\ChatTTS_colab_offline\runtime\lib\site-packages\tn\zh_tn_tagger.fst
INFO:root:                    G:\AI-test\ChatTTS_colab_offline\runtime\lib\site-packages\tn\zh_tn_verbalizer.fst
INFO:root:skip building fst for zh_normalizer ...
speaker_type: seed
Traceback (most recent call last):
  File "G:\AI-test\ChatTTS_colab_offline\runtime\lib\site-packages\gradio\queueing.py", line 521, in process_events
    response = await route_utils.call_process_api(
  File "G:\AI-test\ChatTTS_colab_offline\runtime\lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "G:\AI-test\ChatTTS_colab_offline\runtime\lib\site-packages\gradio\blocks.py", line 1945, in process_api
    result = await self.call_function(
  File "G:\AI-test\ChatTTS_colab_offline\runtime\lib\site-packages\gradio\blocks.py", line 1513, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "G:\AI-test\ChatTTS_colab_offline\runtime\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "G:\AI-test\ChatTTS_colab_offline\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "G:\AI-test\ChatTTS_colab_offline\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "G:\AI-test\ChatTTS_colab_offline\runtime\lib\site-packages\gradio\utils.py", line 831, in wrapper
    response = f(*args, **kwargs)
  File "G:\AI-test\ChatTTS_colab_offline\webui_mix.py", line 299, in generate_tts_audio
    raise e
  File "G:\AI-test\ChatTTS_colab_offline\webui_mix.py", line 280, in generate_tts_audio
    output_files = generate_audio_for_seed(
  File "G:\AI-test\ChatTTS_colab_offline\tts_model.py", line 110, in generate_audio_for_seed
    _params_infer_code = deepcopy(params_infer_code)
  File "G:\AI-test\ChatTTS_colab_offline\runtime\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "G:\AI-test\ChatTTS_colab_offline\runtime\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "G:\AI-test\ChatTTS_colab_offline\runtime\lib\copy.py", line 153, in deepcopy
    y = copier(memo)
  File "G:\AI-test\ChatTTS_colab_offline\runtime\lib\site-packages\torch\_tensor.py", line 86, in __deepcopy__
    raise RuntimeError(
RuntimeError: Only Tensors created explicitly by the user (graph leaves) support the deepcopy protocol at the moment.  If you were attempting to deepcopy a module, this may be because of a torch.nn.utils.weight_norm usage, see https://github.com/pytorch/pytorch/pull/103001

**Comment by 469914294** [comment]
colab上生成语音有错误。
nferring audio for seed=6999:   0% 0/3 [00:00<?, ?steps/s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 532, in process_events
    response = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1928, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1514, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 832, in wrapper
    response = f(*args, **kwargs)
  File "/content/ChatTTS_colab/webui_mix.py", line 213, in audio_interface
    seeds = generate_seeds(num_seeds, texts, progress.tqdm)
  File "/content/ChatTTS_colab/webui_mix.py", line 140, in generate_seeds
    filename = generate_audio_for_seed(chat, seed, texts, 1, 5, "[oral_2][laugh_0][break_4]", None, 0.3, 0.7, 20)
  File "/content/ChatTTS_colab/tts_model.py", line 110, in generate_audio_for_seed
    _params_infer_code = deepcopy(params_infer_code)
  File "/usr/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.10/copy.py", line 153, in deepcopy
    y = copier(memo)
  File "/usr/local/lib/python3.10/dist-packages/torch/_tensor.py", line 86, in __deepcopy__
    raise RuntimeError(
RuntimeError: Only Tensors created explicitly by the user (graph leaves) support the deepcopy protocol at the moment.  If you were attempting to deepcopy a module, this may be because of a torch.nn.utils.weight_norm usage, see https://github.com/pytorch/pytorch/pull/103001

**Comment by kenic123** [comment]
speaker_type: seed
Traceback (most recent call last):
  File "E:\ChatTTS_colab_offline_0.0.6\runtime\lib\site-packages\gradio\queueing.py", line 521, in process_events
    response = await route_utils.call_process_api(
  File "E:\ChatTTS_colab_offline_0.0.6\runtime\lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "E:\ChatTTS_colab_offline_0.0.6\runtime\lib\site-packages\gradio\blocks.py", line 1945, in process_api
    result = await self.call_function(
  File "E:\ChatTTS_colab_offline_0.0.6\runtime\lib\site-packages\gradio\blocks.py", line 1513, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\ChatTTS_colab_offline_0.0.6\runtime\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\ChatTTS_colab_offline_0.0.6\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\ChatTTS_colab_offline_0.0.6\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\ChatTTS_colab_offline_0.0.6\runtime\lib\site-packages\gradio\utils.py", line 831, in wrapper
    response = f(*args, **kwargs)
  File "E:\ChatTTS_colab_offline_0.0.6\webui_mix.py", line 299, in generate_tts_audio
    raise e
  File "E:\ChatTTS_colab_offline_0.0.6\webui_mix.py", line 280, in generate_tts_audio
    output_files = generate_audio_for_seed(
  File "E:\ChatTTS_colab_offline_0.0.6\tts_model.py", line 110, in generate_audio_for_seed
    _params_infer_code = deepcopy(params_infer_code)
  File "E:\ChatTTS_colab_offline_0.0.6\runtime\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "E:\ChatTTS_colab_offline_0.0.6\runtime\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "E:\ChatTTS_colab_offline_0.0.6\runtime\lib\copy.py", line 153, in deepcopy
    y = copier(memo)
  File "E:\ChatTTS_colab_offline_0.0.6\runtime\lib\site-packages\torch\_tensor.py", line 86, in __deepcopy__
    raise RuntimeError(
RuntimeError: Only Tensors created explicitly by the user (graph leaves) support the deepcopy protocol at the moment.  If you were attempting to deepcopy a module, this may be because of a torch.nn.utils.weight_norm usage, see https://github.com/pytorch/pytorch/pull/103001

**Comment by kenic123** [comment]
这个深COPY是个啥东西呀，能运行，但一生成就报错

**Comment by qqkk112** [comment]
raise RuntimeError(
RuntimeError: Only Tensors created explicitly by the user (graph leaves) support the deepcopy protocol at the moment.  If you were attempting to deepcopy a module, this may be because of a torch.nn.utils.weight_norm usage, see https://github.com/pytorch/pytorch/pull/103001

**Comment by qqkk112** [comment]
这个问题谁知道怎么可以解决啊

**Comment by 6drf21e** [comment]
Bug明天修复

**Comment by 6drf21e** [comment]
[0.0.6增量升级包（0.0.4版本前的不支持）fix.zip](https://github.com/user-attachments/files/15934628/0.0.6.0.0.4.fix.zip)
@qqkk112 @kenic123 @Jimi-from-mars @469914294 
已经修复 覆盖原文件即可
如果还有问题请反馈

**Comment by Jimi-from-mars** [comment]
> [0.0.6增量升级包（0.0.4版本前的不支持）fix.zip](https://github.com/user-attachments/files/15934628/0.0.6.0.0.4.fix.zip) @qqkk112 @kenic123 @Jimi-from-mars @469914294 已经修复 覆盖原文件即可 如果还有问题请反馈

感谢大神！！！
