### ISSUE TITLE
mac本地cond部署出现错误Chat.infer() got an unexpected keyword argument 'stream'

### ISSUE THREAD

**Issue by steven1565528** [6drf21e/ChatTTS_colab#56]
speaker_type: role
Traceback (most recent call last):
  File "/Volumes/T9/Anaconda/anaconda3/envs/Chat-tts/lib/python3.11/site-packages/gradio/queueing.py", line 532, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/T9/Anaconda/anaconda3/envs/Chat-tts/lib/python3.11/site-packages/gradio/route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/T9/Anaconda/anaconda3/envs/Chat-tts/lib/python3.11/site-packages/gradio/blocks.py", line 1928, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/T9/Anaconda/anaconda3/envs/Chat-tts/lib/python3.11/site-packages/gradio/blocks.py", line 1526, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/T9/Anaconda/anaconda3/envs/Chat-tts/lib/python3.11/site-packages/gradio/utils.py", line 656, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/T9/Anaconda/anaconda3/envs/Chat-tts/lib/python3.11/site-packages/gradio/utils.py", line 649, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/T9/Anaconda/anaconda3/envs/Chat-tts/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/T9/Anaconda/anaconda3/envs/Chat-tts/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/Volumes/T9/Anaconda/anaconda3/envs/Chat-tts/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/T9/Anaconda/anaconda3/envs/Chat-tts/lib/python3.11/site-packages/gradio/utils.py", line 632, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "/Volumes/T9/Anaconda/anaconda3/envs/Chat-tts/lib/python3.11/site-packages/gradio/utils.py", line 815, in gen_wrapper
    response = next(iterator)
               ^^^^^^^^^^^^^^
  File "/Users/xuxiangxiang/ChatTTS_colab/webui_mix.py", line 382, in generate_tts_audio_stream
    wavs = chat.infer(text, params_infer_code=_params_infer_code, params_refine_text=params_refine_text,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Chat.infer() got an unexpected keyword argument 'stream'

**Comment by 6drf21e** [comment]
需要更新官方包

**Comment by FallenAngels520** [comment]
same question:
TypeError: Chat.load_models() got an unexpected keyword argument 'custom_path'
