### ISSUE TITLE
0.6增量包升级0.5API启动出现 sha256_asset_Decoder_pt 

### ISSUE THREAD

**Issue by shadowzz624** [6drf21e/ChatTTS_colab#57]
INFO:ChatTTS.utils.download:checking assets...
Traceback (most recent call last):
  File "C:\AI\ChatTTS_colab(3)\ChatTTS_colab_offline-0.0.6\ChatTTS_colab_offline\api.py", line 357, in <module>
    chat.load_models(source="local", local_path="models")
  File "C:\AI\ChatTTS_colab(3)\ChatTTS_colab_offline-0.0.6\ChatTTS_colab_offline\ChatTTS\core.py", line 62, in load_models
    if not check_all_assets(update=True):
  File "C:\AI\ChatTTS_colab(3)\ChatTTS_colab_offline-0.0.6\ChatTTS_colab_offline\ChatTTS\utils\download.py", line 63, in check_all_assets
    current_dir, model, os.environ[f"sha256_asset_{menv}"], update
  File "C:\AI\ChatTTS_colab(3)\ChatTTS_colab_offline-0.0.6\ChatTTS_colab_offline\runtime\lib\os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'sha256_asset_Decoder_pt'

**Comment by shadowzz624** [comment]
0.5版本独立运行正常，0.6整合包或者升级包覆盖都出现这个问题。WEB UI正常，问题只出现在API中，WINDOWS 11系统

**Comment by yuanmaitian** [comment]
需要更新加载模型的参数为：chat.load_models(source="custom", custom_path="ChatTTS", compile=False)

**Comment by shadowzz624** [comment]
问题解决，感谢
