### ISSUE TITLE
请问api调用本地模型出现下列错误，请问该如何调整

### ISSUE THREAD

**Issue by wstsr333** [6drf21e/ChatTTS_colab#76]
INFO:ChatTTS.utils.download:checking assets...
Traceback (most recent call last):
  File "/data/chattts/a/c/pi.py", line 358, in <module>
    chat=load_chat_tts_model(source="local", local_path="/data/chattts/chatTTS")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/chattts/a/c/tts_model.py", line 25, in load_chat_tts_model
    chat.load_models(source=source, force_redownload=force_redownload, custom_path=local_path, compile=False)
  File "/data/chattts/a/c/ChatTTS/core.py", line 60, in load_models
    if not check_all_assets(update=True):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/chattts/a/c/ChatTTS/utils/download.py", line 63, in check_all_assets
    current_dir, model, os.environ[f"sha256_asset_{menv}"], update
                        ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 679, in __getitem__

**Comment by wstsr333** [comment]
已经可以了

**Comment by ljt857987** [comment]
大佬，api调用是怎么实现的？我调用api直接返回一个html网页
